name: Update AoC Badges
on:
  workflow_call:
    inputs:
      year:
        required: true
        type: string
    secrets:
      AOC_SESSION_ID:
        required: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 1582899
          session: ${{ secrets.AOC_SESSION_ID }}
          year: ${{ inputs.year }}
          file: 'README.md'
          starsRegex: "(?<=\[stars${{ inputs.year }}\]https:\/\/img\.shields\.io\/badge\/stars%20⭐-)[0-9]+(?=-yellow)"
          daysCompletedRegex: "(?<=\[days${{ inputs.year }}\]https:\/\/img\.shields\.io\/badge\/days%20completed-)[0-9]+(?=-red)"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update badges
          file_pattern: README.md